### ISSUE TITLE
ModuleNotFoundError: No module named 'pymongo'

### ISSUE THREAD

**Issue by mellorjc** [bayesiains/nsf#1]
Thanks for making this publicly available.
I was just trying it out and I get the following error message

> ModuleNotFoundError: No module named 'pymongo'

when running 

```
conda env create -f environment.yml
source activate nsf
python experiments/images.py with experiments/image_configs/imagenet-64-8bit.json
```

is this user error on my part, or should pymongo be in the environment.yml?

**Comment by arturbekasov** [comment]
Yes, pymongo should indeed be in the environment.yml. I've added it now. Thanks for letting us know!
